routes/web.php
<?php

use App\Http\Controllers\TokenController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('token', TokenController::class)->middleware('auth')->except('update', 'edit');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Http/Controllers/TokenController.php
<?php

namespace App\Http\Controllers;

use App\Models\Ability;
use App\Models\User;
use Illuminate\Http\Request;
use Laravel\Sanctum\PersonalAccessToken;

class TokenController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $personal_access_tokens = [];
        foreach (auth()->user()->tokens as $token) {
            array_push($personal_access_tokens, $token);
        }


        return view('token.index', compact('personal_access_tokens'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $users = User::all();

        $abilities = Ability::all();

        return view('token.create', compact('users', 'abilities'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->all());

        if(is_null($request->abilities) || is_null($request->token_name)){
            return back()->with('error', "Please check your inputs");
        }

        $user = auth()->user();
        $personal_token = $user->createToken($request->token_name, $request->abilities)->plainTextToken;

        return back()->with("personal_token", $personal_token);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // $user = User::findOrFail($id)->tokens()->first();
        // // foreach ($user->tokens as $token) {
        // //     dump($token);
        // // }

        // dd($user->token);

        return view('token.show', compact('id'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    protected function validatedData() {



        return $data;
    }
}

resources/views/token/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                @if (session()->get("personal_token"))
                    <div class="card-body">
                        <label for="">
                            Make sure to copy your new personal access token now. You won’t be able to see it again!
                        </label>
                        <br>
                        Personal access token:

                        <div class="alert alert-success" role="alert">
                            {{ session()->get("personal_token") }}
                        </div>
                    </div>
                @else
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                             @if (session()->get("error"))
                                <div class="alert alert-danger fade show" role="alert">
                                    {{ session()->get("error") }}
                                </div>
                            @endif
                        </div>
                        <div class="col-md-12">
                            <form id="form_create_token" action="{{  route('token.store') }}" method="post" >
                                @csrf
                                @method('POST')
                                <div class="form-group">
                                    <label for="">Token Name</label>
                                    <input type="text" name="token_name" class="form-control" required value="{{ old("token_name") }}">
                                </div>

                                {{-- <div class="form-group">
                                    <label for="">Premade Abilities</label>
                                    <select name="" id="" class="form-control">
                                        <option value="">Choose ...</option>
                                        @foreach ($users as $user)
                                            <option value="{{ $user->id }}">{{ $user->name  }}({{ $user->email  }})</option>
                                        @endforeach
                                    </select>
                                </div> --}}


                            </form>
                        </div>

                    </div>

                    <div class="row mt-2">
                        <div class="col-md-12">
                            <h3 class="h3">Scopes/Abilities</h3>
                            <hr>
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th width="10%">Action</th>
                                        <th>Table name</th>
                                        <th>Access</th>
                                        <th>Details</th>
                                    </tr>
                                </thead>
                                <tbody>

                                    @foreach ($abilities as $ability)
                                        <tr>
                                            <td class="text-center">
                                                <input form="form_create_token" type="checkbox" name="abilities[]"class="" value="{{ $ability->name }}">
                                            </td>
                                            <td>
                                                {{ $ability->table_name }}
                                            </td>
                                            <td>
                                                {{ $ability->name }}
                                            </td>
                                            <td>
                                                {{ $ability->details }}
                                            </td>
                                        </tr>
                                    @endforeach

                                </tbody>
                            </table>
                            <div class="row">
                                <div class="col-md-12">
                                    <button type="submit" form="form_create_token" class="btn btn-primary">
                                    Generate Token
                                    </button>
                                </div>

                            </div>
                        </div>

                    </div>

                </div>
                @endif
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/token/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">

                <div class="card-body">
                    @foreach ($personal_access_tokens as $personal_access_token)
                        {{ $personal_access_token->name }} <br>
                        {{-- {{ $personal_access_token->abilities }} --}}
                        @foreach ($personal_access_token->abilities as $ability)
                            {{ $ability }} <br>
                        @endforeach
                        <br>
                    @endforeach
                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/token/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">

                <div class="card-body">
                    <label for="">Make sure to copy your new personal access token now. You won’t be able to see it again!</label> <br>
                    Personal access token:
                    <div class="alert alert-success" role="alert">
                        
                        {{ $id }}
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection